#!/bin/bash

date -u
echo "Stage 0/4"
python3 src/etl/d_character.py &
d_character=$!

python3 src/etl/d_country.py &
d_country=$!

python3 src/etl/d_date.py &
d_date=$!

python3 src/etl/d_department.py &
d_department=$!

python3 src/etl/d_genre.py &
d_genre=$!

python3 src/etl/d_job.py &
d_job=$!

python3 src/etl/d_keyword.py &
d_keyword=$!

python3 src/etl/d_language.py &
d_language=$!

python3 src/etl/d_movie_franchise.py &
d_movie_franchise=$!

python3 src/etl/d_people.py &
d_people=$!

python3 src/etl/d_release_status.py &
d_release_status=$!

python3 src/etl/d_studio.py &
d_studio=$!

python3 src/etl/d_user.py &
d_user=$!

wait $d_character \
     $d_country \
     $d_date \
     $d_department \
     $d_genre \
     $d_job \
     $d_keyword \
     $d_language \
     $d_movie_franchise \
     $d_people \
     $d_release_status \
     $d_studio \
     $d_user

echo "Stage 1/4"
python3 src/etl/d_movie.py &
d_movie=$!

wait $d_movie

echo "Stage 2/4"
python3 src/etl/d_cast.py &
d_cast=$!

python3 src/etl/d_crew.py &
d_crew=$!

python3 src/etl/movie_genres.py &
movie_genres=$!

python3 src/etl/movie_keywords.py &
movie_keywords=$!

python3 src/etl/production_countries.py &
production_countries=$!

python3 src/etl/production_studios.py &
production_studios=$!

python3 src/etl/spoken_languages.py &
spoken_languages=$!

wait $d_cast \
     $d_crew \
     $movie_genres \
     $movie_keywords \
     $production_countries \
     $production_studios \
     $spoken_languages

echo "Stage 3/4"
python3 src/etl/f_movie_popularity.py &
f_movie_popularity=$!

wait $f_movie_popularity

echo "Stage 4/4"
date -u
